filter:
    paths: [src/*]
    excluded_paths: [vendor/*, test/*]
before_commands:
    - 'composer install --dev --prefer-source'
tools:
    external_code_coverage: false
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, test]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, test]
build:
    dependencies:
        before:
            - pecl install pcntl
    environment:
        php:
            version: 5.6.9
    tests:
        override:
            -
                command: ./vendor/bin/codecept run -c tests acceptance
